force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Stores individual workers&apos; compensation claims</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>WC-{YYYY}-{000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Date_Filed__c.field-meta.xml
<CustomField>
    <fullName>Date_Filed__c</fullName>
    <description>date the claim was submitted</description>
    <inlineHelpText>date the claim was submitted</inlineHelpText>
    <label>Date Filed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Days_Open__c.field-meta.xml
<CustomField>
    <fullName>Days_Open__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days Open</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Incident_Date__c.field-meta.xml
<CustomField>
    <fullName>Incident_Date__c</fullName>
    <description>date the workplace incident occurred</description>
    <inlineHelpText>date the workplace incident occurred</inlineHelpText>
    <label>Incident Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Is_High_Value__c.field-meta.xml
<CustomField>
    <fullName>Is_High_Value__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is High Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Settlement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>the amount paid out on the claim</description>
    <inlineHelpText>the amount paid out on the claim</inlineHelpText>
    <label>Settlement Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Date__c</fullName>
    <label>Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>current state of the claim</description>
    <inlineHelpText>current state of the claim</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workers_Comp_Tracker_Threshold__mdt/Workers_Comp_Tracker_Threshold__mdt.object-meta.xml
<CustomObject>
    <description>Stores threshold values used in the Workers Comp Tracker app for setting Employee risk thresholds and for determining whether a claim is high value</description>
    <label>Workers Comp Tracker Threshold</label>
    <pluralLabel>Workers Comp Tracker Thresholds</pluralLabel>
</CustomObject>

force-app/main/default/objects/Workers_Comp_Tracker_Threshold__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Stores the threshold claim quantity or settlement amount value</description>
    <inlineHelpText>Stores the threshold claim quantity or settlement amount value</inlineHelpText>
    <label>Value</label>
    <precision>9</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClaimTriggerHandler.cls
/**
 * Claim Trigger Handler
 * Extends the virtual TriggerHandler framework class and overrides the context methods
 * TriggerHandler Source: https://github.com/kevinohara80/sfdc-trigger-framework
 * @see <a href="https://www.apexhours.com/trigger-framework-in-salesforce/">Trigger Frameworks in Salesforce</a>
 */
public with sharing class ClaimTriggerHandler extends TriggerHandler {


public override void beforeInsert(){
           determineIsHighValue(Trigger.new);
           calculateDaysOpen(Trigger.new);
           validateSettlementAmount(Trigger.new);
           verifyDates(Trigger.new);
}


public override void beforeUpdate(){
            determineIsHighValue(Trigger.new);
            calculateDaysOpen(Trigger.new);
            determineSettlementDate(Trigger.new);
            validateSettlementAmount(Trigger.new);
            verifyDates(Trigger.new);
}

// REQUIREMENT #1 
//High-Value Claim Flag
// Automatically check the Is High Value Checkbox field whenever the Settlement Amount exceeds a threshold we define in Custom metadata
// TBD: Need to confirm with stakeholders if settlement amount = threshold value, should claim be marked as highvalue? Current logic sets the field to high value if settlement date is equal to threshold.


private void determineIsHighValue (List<Claim__c> claims) {
           
    Workers_Comp_Tracker_Threshold__mdt hvc = Workers_Comp_Tracker_Threshold__mdt.getInstance('High_Value_Claim');
 
    if (hvc == null){
           return;
    }
   
     for (Claim__c claim : claims) {
     
         if (claim.Settlement_Amount__c >= hvc.Value__c ){
                    claim.Is_High_Value__c = true;
         }else {
                    claim.Is_High_Value__c = false;
         }

     }
 }


// REQUIREMENT #2
//Claim Duration Tracking
//Calculates the number of days between the Incident Date and today (or the Date Filed if the claim is Settled or Denied) and stores it Days Open field on Claim object
// TBD: Should 'Closed' claims stop counting at Date Filed (like Settled/Denied)?
//TBD: Shouldn't this use Claim__c.Settlement_Date__c if the status = Settled?

    private void calculateDaysOpen(List<Claim__c> claims){

        for( claim__c c : claims) {   
            
        if ( c.Incident_Date__c != null )
        {           
             if(c.Status__c == 'Settled' || c.Status__c == 'Denied') {             
                   if (c.Date_Filed__c != null ) 
                    {
                        
                        c.Days_Open__c = c.Incident_Date__c.daysBetween(c.Date_Filed__c);
                    }
                 
             } else { 
   
                        c.Days_Open__c = c.Incident_Date__c.daysBetween(date.today());
             }

         }
        }
    }


//REQUIREMENT #3
//Claim Status Automation
//When Status changes to Settled: set Settlement Date to today if it is currently blank. 
//When Status changes to Denied: clear the Settlement Amount field (set it to 0)


 private void determineSettlementDate( List<Claim__c> claims) 
  {

         Map<Id, Claim__c> oldClaims = (Map<Id, Claim__c>) Trigger.oldMap;
                      

        for (Claim__c  c : claims)
        {

            if( c.Status__c == 'Settled' &&  oldClaims.get(c.Id).Status__c != 'Settled')
             {
                   if( c.Settlement_Date__c == null)
                    {
                         c.Settlement_Date__c = Date.today();
                     } 

            } else if ( c.Status__c == 'Denied' && oldClaims.get(c.Id).Status__C != 'Denied' ) 
                     {
                     
                         c.Settlement_Amount__c = 0;

                     }  
              }

         }

//Requirement 4:
//Validate that Settlement Amount is greater than zero — a claim cannot be marked Settled with a $0 payout.

private void validateSettlementAmount (List<Claim__c> claims) {

        for (Claim__c  c : claims) {

              if(c.Settlement_Amount__c <= 0 && c.Status__c == 'Settled'){
                          c.addError('A claim cannot have status of Settled if the Settlement Amount is 0');

              } 

            }
        }

//REQUIREMENT 5:
//Validate that Incident Date is not in the future and is not after the Date Filed — a realistic claim cannot be reported before it happened.

private void verifyDates (List<Claim__c> claims){

 for (Claim__c c : claims){
        
         if(c.Incident_Date__c != null && c.Incident_Date__c > Date.today()) {
                               c.addError('Incident Date should not be in the future');
         }
        
         if(c.Incident_Date__c != null && c.Date_Filed__c != null){
             if( c.Incident_Date__c > c.Date_Filed__c){
                            c.addError('Incident Date should not be after the Date filed'); 
          }
         }                     

 }

}



}
    //---------------Logic with helper class--------------------------------------
    // Local copies of the Trigger context variables
  //  private List<Claim__c> newClaims;
   // private List<Claim__c> oldClaims;
   // private Map<Id, Claim__c> oldClaimsMap;

    /**
     * CONSTRUCTOR
     * Handles the necessary type casting for Trigger context variables referenced in a class
     */
  //  public ClaimTriggerHandler() {
        // Constructor takes care of the 
   //     this.newClaims = (List<Claim__c>) Trigger.new;
  //  }

    /**
     * BEFORE_INSERT
     */
//    public override void beforeInsert(){
    //    ClaimHelper.verifyDates(newClaims);
  //      ClaimHelper.calculateDaysOpen(newClaims);
  //      ClaimHelper.determineIsHighValue(newClaims);
   //     ClaimHelper.determineSettlementDate(newClaims);
  //  }

    /**
     * BEFORE_UPDATE
     */
   // public override void beforeUpdate(){
 //       ClaimHelper.verifyDates(newClaims);
  //      ClaimHelper.calculateDaysOpen(newClaims);
   //     ClaimHelper.determineIsHighValue(newClaims);
  //      ClaimHelper.determineSettlementDate(newClaims);
 //   }