force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Stores individual workers&apos; compensation claims</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>WC-{YYYY}-{000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Date_Filed__c.field-meta.xml
<CustomField>
    <fullName>Date_Filed__c</fullName>
    <description>date the claim was submitted</description>
    <inlineHelpText>date the claim was submitted</inlineHelpText>
    <label>Date Filed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Days_Open__c.field-meta.xml
<CustomField>
    <fullName>Days_Open__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days Open</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Incident_Date__c.field-meta.xml
<CustomField>
    <fullName>Incident_Date__c</fullName>
    <description>date the workplace incident occurred</description>
    <inlineHelpText>date the workplace incident occurred</inlineHelpText>
    <label>Incident Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Is_High_Value__c.field-meta.xml
<CustomField>
    <fullName>Is_High_Value__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is High Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Settlement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>the amount paid out on the claim</description>
    <inlineHelpText>the amount paid out on the claim</inlineHelpText>
    <label>Settlement Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Date__c</fullName>
    <label>Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>current state of the claim</description>
    <inlineHelpText>current state of the claim</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workers_Comp_Tracker_Threshold__mdt/Workers_Comp_Tracker_Threshold__mdt.object-meta.xml
<CustomObject>
    <description>Stores threshold values used in the Workers Comp Tracker app for setting Employee risk thresholds and for determining whether a claim is high value</description>
    <label>Workers Comp Tracker Threshold</label>
    <pluralLabel>Workers Comp Tracker Thresholds</pluralLabel>
</CustomObject>

force-app/main/default/objects/Workers_Comp_Tracker_Threshold__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Stores the threshold claim quantity or settlement amount value</description>
    <inlineHelpText>Stores the threshold claim quantity or settlement amount value</inlineHelpText>
    <label>Value</label>
    <precision>9</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClaimHelper.cls
/**
 * Claim trigger Helper
 * Contains the utility logic called by the ClaimTriggerHandler
 */
public with sharing class ClaimHelper {
    /**
     * Determine if the Claim is high value based on the Settlement amount
     * @param claims a list of Claim records
     */
    public static void determineIsHighValue(List<Claim__c> claims){
        Workers_Comp_Tracker_Threshold__mdt threshold = Workers_Comp_Tracker_Threshold__mdt.getInstance('High_Value_Claim');
        for(Claim__c claim : claims){
            if (claim.Settlement_Amount__c != null && claim.Settlement_Amount__c >= threshold.Value__c){
                claim.Is_High_Value__c = true;
            }
            else{
                claim.Is_High_Value__c = false;
            }
        }
    }

    /**
     * Calculate the number of days the Claim has been open
     * @param claims a list of Claim records
     */
    public static void calculateDaysOpen(List<Claim__c> claims){
        for(Claim__c claim : claims){
            if (claim.Status__c == 'Settled' || claim.Status__c == 'Denied'){
                claim.Days_Open__c = claim.Incident_Date__c.daysBetween(claim.Date_Filed__c);
            }
            else{
                claim.Days_Open__c = claim.Incident_Date__c.daysBetween(Date.today());
            }
        }
    }

    /**
     * Verify claim date field values are valid and show error to the user if they are not
     * @param claims a list of Claim records
     */
    public static void verifyDates(List<Claim__c> claims){
        for(Claim__c claim : claims){
            if (claim.Date_Filed__c > Date.today() || claim.Incident_Date__c > Date.today() || claim.Settlement_Date__c > Date.today()){
                claim.addError('Date Filed, Incident Date, or Settlement Date fields cannot be in the future');
            }
            if(claim.Incident_Date__c > claim.Date_Filed__c){
                claim.addError('Incident Date cannot be after the Date Filed - claims cannot be reported before they happen');
            }
        }
    }

    /**
     * Populate the Settlement Amount on claim status change
     * @param claims a list of Claim records
     */
    public static void determineSettlementDate(List<Claim__c> claims){
        for(Claim__c claim : claims){
            if (claim.Status__c == 'Settled' && claim.Settlement_Date__c == null){
                if(claim.Settlement_Amount__c > 0){
                    claim.Settlement_Date__c = Date.today();
                }
                else{
                    claim.addError('A claim cannot have status of Settled if the Settlement Amount is 0');
                }
            }
            if(claim.Status__c == 'Denied' && claim.Settlement_Amount__c != 0){
                claim.Settlement_Amount__c = 0;
                claim.Settlement_Date__c = null;
            }
        }
    }
}