force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Stores individual workers&apos; compensation claims</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>WC-{YYYY}-{000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Insurance_Provider__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the insurance company handling this claim</description>
    <inlineHelpText>the insurance company handling this claim</inlineHelpText>
    <label>Insurance Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Settlement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>the amount paid out on the claim</description>
    <inlineHelpText>the amount paid out on the claim</inlineHelpText>
    <label>Settlement Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Represent the employees of the company that may file workers&apos; comp claims</description>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>Risk_Level__c</fullName>
    <label>Risk Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Medium Risk</fullName>
            </value>
            <value>
                <fullName>High Risk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Total_Claims__c.field-meta.xml
<CustomField>
    <fullName>Total_Claims__c</fullName>
    <defaultValue>0</defaultValue>
    <description>How many claims this employee has been involved in across all time</description>
    <inlineHelpText>How many claims this employee has been involved in across all time</inlineHelpText>
    <label>Total Claims</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Total_Settlement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Settlement_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Tracks the sum of all settled claim payouts this employee is associated with</description>
    <inlineHelpText>Tracks the sum of all settled claim payouts this employee is associated with</inlineHelpText>
    <label>Total Settlement Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Claim__c/Employee_Claim__c.object-meta.xml
<CustomObject>
    <description>Junction object that links Employees to Claims. This object enables a many-to-many relationship, which is needed because a single claim can involve multiple employees (e.g., a group accident) and an employee can have multiple claims over time.</description>
    <label>Employee Claim</label>
    <nameField>
        <displayFormat>EC-{YY}{MM}{DD}-{00}</displayFormat>
        <label>Employee Claim</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Claim__c/fields/Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Claim_Number__c</fullName>
    <label>Claim Number</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Employee Claim</relationshipLabel>
    <relationshipName>Employee_Claim</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Claim__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Claim</relationshipLabel>
    <relationshipName>Employee_Claim</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Workers_Comp_Tracker_Threshold__mdt/Workers_Comp_Tracker_Threshold__mdt.object-meta.xml
<CustomObject>
    <description>Stores threshold values used in the Workers Comp Tracker app for setting Employee risk thresholds and for determining whether a claim is high value</description>
    <label>Workers Comp Tracker Threshold</label>
    <pluralLabel>Workers Comp Tracker Thresholds</pluralLabel>
</CustomObject>

force-app/main/default/objects/Workers_Comp_Tracker_Threshold__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Stores the threshold claim quantity or settlement amount value</description>
    <inlineHelpText>Stores the threshold claim quantity or settlement amount value</inlineHelpText>
    <label>Value</label>
    <precision>9</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EmployeeClaimHelper - Copy.cls
//Testing braching and merging

/**
 * Employee Claim trigger Helper
 * Contains utility logic called by the EmployeeClaimTriggerHandler and other classes
 */
public with sharing class EmployeeClaimHelper {
    /**
     * Retrieve a unique collection of Employee record Ids from the provided Employee Claims
     * @param employeeClaims a list of the Employee Claim records involved in the trigger context
     * @return a Set of Employee record Ids
     */
    public static Set<Id> getEmployeeIds(List<Employee_Claim__c> employeeClaims){
        Set<Id> employeeIds = new Set<Id>();
        for(Employee_Claim__c ec : employeeClaims){
            if(ec.Employee_Name__c != null){
                employeeIds.add(ec.Employee_Name__c);
            }
        }
        return employeeIds;
    }
    
    /**
     * Update the Employee risk level, total claims, and total settlement amount calculated from all their related Claims
     * @param employeeIds a set of Employee record Ids
     */
    public static void updateEmployeeRiskAndTotals(Set<Id> employeeIds){
        // Get all related Claims grouped by Employee and Insurance Provider to allow provider-level risk assessment
        List<AggregateResult> employeeProviderTotals = [SELECT Employee_Name__c, Claim_Number__r.Insurance_Provider__c, COUNT(Id) providerClaims, SUM(Claim_Number__r.Settlement_Amount__c) providerSettlementAmount
                                                FROM Employee_Claim__c 
                                                WHERE Employee_Name__c IN :employeeIds 
                                                GROUP BY Employee_Name__c, Claim_Number__r.Insurance_Provider__c
                                                ORDER BY Employee_Name__c];

        // Since query results are sub-grouped by provider, it is possible for the same employee Id to have multiple aggregate result entries with different providers
        // A map will allow claim and settlement total accumulation and highest risk level detection across providers for the same employee
        Map<Id, Employee__c> employeeMap = new Map<Id, Employee__c>();

        // Loop aggregate query results
        for(AggregateResult employeeProviderTotal : employeeProviderTotals){
            // Store provider-level claims and settlement values in an Employee variable then check risk level for this provider
            Employee__c employeeProvider = new Employee__c();
            employeeProvider.Id = (Id)employeeProviderTotal.get('Employee_Name__c');
            employeeProvider.Total_Claims__c = (Decimal)employeeProviderTotal.get('providerClaims');
            employeeProvider.Total_Settlement_Amount__c = (Decimal)employeeProviderTotal.get('providerSettlementAmount');
            employeeProvider.Risk_Level__c = calculateProviderRiskLevel(employeeProvider.Total_Claims__c, employeeProvider.Total_Settlement_Amount__c);

            // If this Employee has already been added to the map, then update it with new values, otherwise add to the map
            if(employeeMap.containsKey(employeeProvider.Id)){
                Employee__c mapEmployee = employeeMap.get(employeeProvider.Id);
                mapEmployee.Total_Claims__c += employeeProvider.Total_Claims__c;
                mapEmployee.Total_Settlement_Amount__c += employeeProvider.Total_Settlement_Amount__c;
                if(mapEmployee.Risk_Level__c == null || mapEmployee.Risk_Level__c == 'Standard' || (mapEmployee.Risk_Level__c == 'Medium Risk' && employeeProvider.Risk_Level__c == 'High Risk')){
                    mapEmployee.Risk_Level__c = employeeProvider.Risk_Level__c;
                }
                employeeMap.put(employeeProvider.Id, mapEmployee);
            }
            else{ // It hasn't been added to the map yet
                employeeMap.put(employeeProvider.Id, employeeProvider);
            }
        }

        // Update the Employee records with values contained in the map
        if(!employeeMap.isEmpty()){
            update employeeMap.values();
        }
    }

    /**
     * Calculate the risk level given a claim quantity and total payout to an Employee from a single Insurance Provider
     * @param numClaims the number of Claims on a single Insurance Provider
     * @param settlementAmount the total Settlement Amount received from a single Insurance Provider
     * @return string representing the Employee record risk level picklist value
     */
    private static String calculateProviderRiskLevel(Decimal numClaims, Decimal settlementAmount){
        // Get all the risk threshold values to check
        Decimal highClaimQty = Workers_Comp_Tracker_Threshold__mdt.getInstance('High_Risk_Claim_Quantity').Value__c;
        Decimal highPayout = Workers_Comp_Tracker_Threshold__mdt.getInstance('High_Risk_Total_Payout').Value__c;
        Decimal mediumClaimQty = Workers_Comp_Tracker_Threshold__mdt.getInstance('Medium_Risk_Claim_Quantity').Value__c;
        Decimal mediumPayout = Workers_Comp_Tracker_Threshold__mdt.getInstance('Medium_Risk_Total_Payout').Value__c;

        if(numClaims >= highClaimQty || settlementAmount >= highPayout){
            return 'High Risk';
        }
        else if(numClaims >= mediumClaimQty || settlementAmount >= mediumPayout){
            return 'Medium Risk';
        }
        else{
            return 'Standard';
        }
    }
}