force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Stores individual workers&apos; compensation claims</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>WC-{YYYY}-{000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Date_Filed__c.field-meta.xml
<CustomField>
    <fullName>Date_Filed__c</fullName>
    <description>date the claim was submitted</description>
    <inlineHelpText>date the claim was submitted</inlineHelpText>
    <label>Date Filed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Incident_Date__c.field-meta.xml
<CustomField>
    <fullName>Incident_Date__c</fullName>
    <description>date the workplace incident occurred</description>
    <inlineHelpText>date the workplace incident occurred</inlineHelpText>
    <label>Incident Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Injury_Type__c.field-meta.xml
<CustomField>
    <fullName>Injury_Type__c</fullName>
    <label>Injury Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Equipment Malfunction</fullName>
            </value>
            <value>
                <fullName>Repetitive Motion</fullName>
            </value>
            <value>
                <fullName>Slip and Fall</fullName>
            </value>
            <value>
                <fullName>Struck By Object</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Provider__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the insurance company handling this claim</description>
    <inlineHelpText>the insurance company handling this claim</inlineHelpText>
    <label>Insurance Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Settlement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>the amount paid out on the claim</description>
    <inlineHelpText>the amount paid out on the claim</inlineHelpText>
    <label>Settlement Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>current state of the claim</description>
    <inlineHelpText>current state of the claim</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Represent the employees of the company that may file workers&apos; comp claims</description>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Hire_Date__c.field-meta.xml
<CustomField>
    <fullName>Hire_Date__c</fullName>
    <label>Hire Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>Risk_Level__c</fullName>
    <label>Risk Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Medium Risk</fullName>
            </value>
            <value>
                <fullName>High Risk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Total_Claims__c.field-meta.xml
<CustomField>
    <fullName>Total_Claims__c</fullName>
    <defaultValue>0</defaultValue>
    <description>How many claims this employee has been involved in across all time</description>
    <inlineHelpText>How many claims this employee has been involved in across all time</inlineHelpText>
    <label>Total Claims</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Total_Settlement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Settlement_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Tracks the sum of all settled claim payouts this employee is associated with</description>
    <inlineHelpText>Tracks the sum of all settled claim payouts this employee is associated with</inlineHelpText>
    <label>Total Settlement Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Claim__c/Employee_Claim__c.object-meta.xml
<CustomObject>
    <description>Junction object that links Employees to Claims. This object enables a many-to-many relationship, which is needed because a single claim can involve multiple employees (e.g., a group accident) and an employee can have multiple claims over time.</description>
    <label>Employee Claim</label>
    <nameField>
        <displayFormat>EC-{YY}{MM}{DD}-{00}</displayFormat>
        <label>Employee Claim</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Claim__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Claim</relationshipLabel>
    <relationshipName>Employee_Claim</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Workers_Comp_Tracker_Threshold__mdt/Workers_Comp_Tracker_Threshold__mdt.object-meta.xml
<CustomObject>
    <description>Stores threshold values used in the Workers Comp Tracker app for setting Employee risk thresholds and for determining whether a claim is high value</description>
    <label>Workers Comp Tracker Threshold</label>
    <pluralLabel>Workers Comp Tracker Thresholds</pluralLabel>
</CustomObject>

force-app/main/default/objects/Workers_Comp_Tracker_Threshold__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Stores the threshold claim quantity or settlement amount value</description>
    <inlineHelpText>Stores the threshold claim quantity or settlement amount value</inlineHelpText>
    <label>Value</label>
    <precision>9</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestEmployeeClaimHelper.cls
/**
 * Unit tests for the EmployeeClaimHelper class
 * NOTE: most tests for the updateEmployeeRiskAndTotals method are covered in the TestEmployeeClaimHandler
 * @see EmployeeClaimHelper
 */
@isTest
private class TestEmployeeClaimHelper {
    /** Test Data Setup */
    @TestSetup static void setup(){
        List<Account> providers = new List<Account>();
        providers.add(new Account(Name = 'Provider 1'));
        providers.add(new Account(Name = 'Provider 2'));
        insert providers;

        List<Employee__c> employees = new List<Employee__c>();
        Employee__c employee1 = new Employee__c();
            employee1.Name = 'Employee 1';
            employee1.Hire_Date__c = Date.today();
            employees.add(employee1);
        Employee__c employee2 = employee1.clone();
            employee2.Name = 'Employee 2';
            employees.add(employee2);
        insert employees;

        List<Claim__c> claims = new List<Claim__c>();
        for (Integer i = 0; i < 3; i++){
            Claim__c claim = new Claim__c();
            claim.Incident_Date__c = Date.today() - i;
            claim.Date_Filed__c = Date.today() - i;
            claim.Injury_Type__c = 'Repetitive Motion';
            claim.Status__c = 'Settled';
            claim.Settlement_Amount__c = 1000;
            claim.Insurance_Provider__c = providers[0].Id;
            claims.add(claim);
        }

        claims[1].Insurance_Provider__c = providers[1].Id; // Assign 1 claim to the other provider
        insert claims;
    }

    /** Test getEmployeeIds with a variety of input scenarios */
    @IsTest
    static void testGetEmployeeIds() {
        List<Employee_Claim__c> employeeClaims;

        // Null input
        Set<Id> employeeIds = EmployeeClaimHelper.getEmployeeIds(employeeClaims);
        Assert.isTrue(employeeIds.isEmpty(), 'Expected no employee Ids');

        // Empty input
        employeeClaims = new List<Employee_Claim__c>();
        employeeIds = EmployeeClaimHelper.getEmployeeIds(employeeClaims);
        Assert.isTrue(employeeIds.isEmpty(), 'Expected no employee Ids');

        // Single values in input list
        List<Employee__c> employees = [SELECT Id FROM Employee__c];
        employeeClaims.add(new Employee_Claim__c(Employee_Name__c = employees[0].Id));
        employeeIds = EmployeeClaimHelper.getEmployeeIds(employeeClaims);
        Assert.areEqual(1, employeeIds.size(), 'Expected 1 unique Employee Id');

        // Multiple claims for same employee in input list
        employeeClaims.add(new Employee_Claim__c(Employee_Name__c = employees[0].Id));
        employeeIds = EmployeeClaimHelper.getEmployeeIds(employeeClaims);
        Assert.areEqual(1, employeeIds.size(), 'Expected 1 unique Employee Ids');

        // Include second employee in claims list
        employeeClaims.add(new Employee_Claim__c(Employee_Name__c = employees[1].Id));
        employeeIds = EmployeeClaimHelper.getEmployeeIds(employeeClaims);
        Assert.areEqual(2, employeeIds.size(), 'Expected 2 unique Employee Ids');
    }

    /** Test calculateProviderRiskLevel with a variety of input scenarios */
    @IsTest
    static void testCalculateProviderRiskLevel() {
        // Get all the risk threshold values to check
        Decimal highClaimQty = Workers_Comp_Tracker_Threshold__mdt.getInstance('High_Risk_Claim_Quantity').Value__c;
        Decimal highPayout = Workers_Comp_Tracker_Threshold__mdt.getInstance('High_Risk_Total_Payout').Value__c;
        Decimal mediumClaimQty = Workers_Comp_Tracker_Threshold__mdt.getInstance('Medium_Risk_Claim_Quantity').Value__c;
        Decimal mediumPayout = Workers_Comp_Tracker_Threshold__mdt.getInstance('Medium_Risk_Total_Payout').Value__c;

        // Null input
        Decimal numClaims;
        Decimal settlementAmount;
        String riskLevel = EmployeeClaimHelper.calculateProviderRiskLevel(numClaims, settlementAmount);
        Assert.areEqual('Standard', riskLevel, 'Expected risk level Standard');

        // Negative input
        numClaims = -1;
        settlementAmount = -1000.0;
        riskLevel = EmployeeClaimHelper.calculateProviderRiskLevel(numClaims, settlementAmount);
        Assert.areEqual('Standard', riskLevel, 'Expected risk level Standard');

        // Zero input
        numClaims = 0;
        settlementAmount = 0.0;
        riskLevel = EmployeeClaimHelper.calculateProviderRiskLevel(numClaims, settlementAmount);
        Assert.areEqual('Standard', riskLevel, 'Expected risk level Standard');

        // Medium Claim quantity
        numClaims = mediumClaimQty;
        settlementAmount = 0.0;
        riskLevel = EmployeeClaimHelper.calculateProviderRiskLevel(numClaims, settlementAmount);
        Assert.areEqual('Medium Risk', riskLevel, 'Expected risk level Medium Risk');

        // Medium Settlement amount
        numClaims = 0;
        settlementAmount = mediumPayout;
        riskLevel = EmployeeClaimHelper.calculateProviderRiskLevel(numClaims, settlementAmount);
        Assert.areEqual('Medium Risk', riskLevel, 'Expected risk level Medium Risk');

        // High Claim quantity
        numClaims = highClaimQty;
        settlementAmount = 0.0;
        riskLevel = EmployeeClaimHelper.calculateProviderRiskLevel(numClaims, settlementAmount);
        Assert.areEqual('High Risk', riskLevel, 'Expected risk level High Risk');

        // High Settlement amount
        numClaims = 0;
        settlementAmount = highPayout;
        riskLevel = EmployeeClaimHelper.calculateProviderRiskLevel(numClaims, settlementAmount);
        Assert.areEqual('High Risk', riskLevel, 'Expected risk level High Risk');
    }

    /** Test the updateEmployeeRiskAndTotals method */
    @IsTest
    static void testUpdateEmployeeRiskAndTotals() {
        // Null input
        Set<Id> employeeIds;
        EmployeeClaimHelper.updateEmployeeRiskAndTotals(employeeIds);

        // Empty input
        employeeIds = new Set<Id>();
        EmployeeClaimHelper.updateEmployeeRiskAndTotals(employeeIds);
    }

    /** Test the generateEmployeeUpdateMap method */
    @IsTest
    static void testGenerateEmployeeUpdateMap(){
        // Get all the risk threshold values to check
        Decimal highClaimQty = Workers_Comp_Tracker_Threshold__mdt.getInstance('High_Risk_Claim_Quantity').Value__c;
        Decimal highPayout = Workers_Comp_Tracker_Threshold__mdt.getInstance('High_Risk_Total_Payout').Value__c;
        Decimal mediumClaimQty = Workers_Comp_Tracker_Threshold__mdt.getInstance('Medium_Risk_Claim_Quantity').Value__c;
        Decimal mediumPayout = Workers_Comp_Tracker_Threshold__mdt.getInstance('Medium_Risk_Total_Payout').Value__c;

        // Retrieve test Employee data
        List<Employee__c> employees = [SELECT Id, Name FROM Employee__c];
        Id firstEmployeeId = employees[0].Id;
        Set<Id> employeeIds = new Map<Id, Employee__c>(employees).keySet();
        List<EmployeeClaimHelper.EmployeeProviderTotal> employeeProviderTotals = new List<EmployeeClaimHelper.EmployeeProviderTotal>();

        // Scenario: no query results found for this employee
        System.debug('Scenario: No Employee Claims');
        Map<Id, Employee__c> employeeMap = EmployeeClaimHelper.generateEmployeeUpdateMap(employeeIds, employeeProviderTotals);
        for(Id employeeId : employeeIds){
            Assert.areEqual(0, employeeMap.get(firstEmployeeId).Total_Claims__c, 'Expected 0 claims');
            Assert.areEqual(0, employeeMap.get(firstEmployeeId).Total_Settlement_Amount__c, 'Expected 0 settlement amount');
            Assert.areEqual('Standard', employeeMap.get(firstEmployeeId).Risk_Level__c, 'Expected Standard risk');
        }

        // Scenario: Claim not settled (don't consider settlement amount until settled)
        System.debug('Scenario: Claim not Settled');
        EmployeeClaimHelper.EmployeeProviderTotal ept = new EmployeeClaimHelper.EmployeeProviderTotal();
            ept.employee = firstEmployeeId;
            ept.status = 'Open';
            ept.providerClaims = mediumClaimQty - 1;
            ept.providerSettlementAmount = highPayout;
            employeeProviderTotals.add(ept);
        employeeMap = EmployeeClaimHelper.generateEmployeeUpdateMap(employeeIds, employeeProviderTotals);
        Assert.areEqual(mediumClaimQty - 1, employeeMap.get(firstEmployeeId).Total_Claims__c, 'Expected 1 less than medium threshold claim qty');
        Assert.areEqual(0, employeeMap.get(firstEmployeeId).Total_Settlement_Amount__c, 'Expected 0 settlement amount since claims are open');
        Assert.areEqual('Standard', employeeMap.get(firstEmployeeId).Risk_Level__c, 'Expected Standard risk');

        // Scenario: standard payout & claim qty risk
        System.debug('Scenario: Standard Claim Quantity and Payout Risk');
        employeeProviderTotals.clear();
            ept.employee = firstEmployeeId;
            ept.status = 'Settled';
            ept.providerClaims = mediumClaimQty - 1;
            ept.providerSettlementAmount = mediumPayout - 1;
            employeeProviderTotals.add(ept);
        employeeMap = EmployeeClaimHelper.generateEmployeeUpdateMap(employeeIds, employeeProviderTotals);
        Assert.areEqual(mediumClaimQty - 1, employeeMap.get(firstEmployeeId).Total_Claims__c, 'Expected 1 less than medium threshold claim qty');
        Assert.areEqual(mediumPayout - 1, employeeMap.get(firstEmployeeId).Total_Settlement_Amount__c, 'Expected 1 less than medium threshold payout');
        Assert.areEqual('Standard', employeeMap.get(firstEmployeeId).Risk_Level__c, 'Expected Standard risk');

        // Scenario: medium claim quantity risk
        System.debug('Scenario: Medium Claim Quantity Risk');
        employeeProviderTotals.clear();
            ept.employee = firstEmployeeId;
            ept.status = 'Settled';
            ept.providerClaims = mediumClaimQty;
            ept.providerSettlementAmount = mediumPayout - 1;
            employeeProviderTotals.add(ept);
        employeeMap = EmployeeClaimHelper.generateEmployeeUpdateMap(employeeIds, employeeProviderTotals);
        Assert.areEqual(mediumClaimQty, employeeMap.get(firstEmployeeId).Total_Claims__c, 'Expected the medium threshold claim qty');
        Assert.areEqual(mediumPayout - 1, employeeMap.get(firstEmployeeId).Total_Settlement_Amount__c, 'Expected 1 less than medium threshold payout');
        Assert.areEqual('Medium Risk', employeeMap.get(firstEmployeeId).Risk_Level__c, 'Expected Medium risk');

        // Scenario: high claim quantity risk
        System.debug('Scenario: High Claim Quantity Risk');
        employeeProviderTotals.clear();
            ept.employee = firstEmployeeId;
            ept.status = 'Settled';
            ept.providerClaims = highClaimQty;
            ept.providerSettlementAmount = mediumPayout - 1;
            employeeProviderTotals.add(ept);
        employeeMap = EmployeeClaimHelper.generateEmployeeUpdateMap(employeeIds, employeeProviderTotals);
        Assert.areEqual(highClaimQty, employeeMap.get(firstEmployeeId).Total_Claims__c, 'Expected the high threshold claim qty');
        Assert.areEqual(mediumPayout - 1, employeeMap.get(firstEmployeeId).Total_Settlement_Amount__c, 'Expected 1 less than medium threshold payout');
        Assert.areEqual('High Risk', employeeMap.get(firstEmployeeId).Risk_Level__c, 'Expected High risk');

        // Scenario: medium payout risk
        System.debug('Scenario: Medium Payout Risk');
        employeeProviderTotals.clear();
            ept.employee = firstEmployeeId;
            ept.status = 'Settled';
            ept.providerClaims = mediumClaimQty - 1;
            ept.providerSettlementAmount = mediumPayout;
            employeeProviderTotals.add(ept);
        employeeMap = EmployeeClaimHelper.generateEmployeeUpdateMap(employeeIds, employeeProviderTotals);
        Assert.areEqual(mediumClaimQty -1, employeeMap.get(firstEmployeeId).Total_Claims__c, 'Expected 1 less than the medium threshold claim qty');
        Assert.areEqual(mediumPayout, employeeMap.get(firstEmployeeId).Total_Settlement_Amount__c, 'Expected the medium threshold payout');
        Assert.areEqual('Medium Risk', employeeMap.get(firstEmployeeId).Risk_Level__c, 'Expected Medium risk');

        // Scenario: high payout risk
        System.debug('Scenario: High Payout Risk');
        employeeProviderTotals.clear();
            ept.employee = firstEmployeeId;
            ept.status = 'Settled';
            ept.providerClaims = mediumClaimQty - 1;
            ept.providerSettlementAmount = highPayout;
            employeeProviderTotals.add(ept);
        employeeMap = EmployeeClaimHelper.generateEmployeeUpdateMap(employeeIds, employeeProviderTotals);
        Assert.areEqual(mediumClaimQty -1, employeeMap.get(firstEmployeeId).Total_Claims__c, 'Expected 1 less than the medium threshold claim qty');
        Assert.areEqual(highPayout, employeeMap.get(firstEmployeeId).Total_Settlement_Amount__c, 'Expected the high threshold payout');
        Assert.areEqual('High Risk', employeeMap.get(firstEmployeeId).Risk_Level__c, 'Expected High risk');
    }
}